// <auto-generated />
using System;
using Atlob_Dent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atlob_Dent.Migrations
{
    [DbContext(typeof(Atlob_dentEntities))]
    [Migration("20191124203913_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("Atlob_Dent.Data.Admin", b =>
                {
                    b.Property<string>("phone")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("fullname")
                        .IsRequired();

                    b.Property<string>("role")
                        .IsRequired();

                    b.HasKey("phone");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Category", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<Guid?>("superId");

                    b.HasKey("id");

                    b.HasIndex("superId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Comment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("message")
                        .IsRequired();

                    b.Property<string>("phone")
                        .IsRequired();

                    b.HasKey("id");

                    b.HasIndex("phone");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Company", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("imgsrc");

                    b.Property<string>("name")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Atlob_Dent.Data.OnSale", b =>
                {
                    b.Property<Guid>("productId");

                    b.Property<int>("disPeriod");

                    b.Property<double>("discount");

                    b.HasKey("productId");

                    b.ToTable("OnSales");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Order", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address")
                        .IsRequired();

                    b.Property<string>("fullname")
                        .IsRequired();

                    b.Property<DateTime>("orderDate");

                    b.Property<string>("phone")
                        .IsRequired();

                    b.Property<Guid>("productId");

                    b.Property<int>("quantity");

                    b.Property<int>("state");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Product", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("categoryId");

                    b.Property<Guid>("companyId");

                    b.Property<DateTime>("createdDate");

                    b.Property<string>("desc");

                    b.Property<string>("images_url")
                        .IsRequired();

                    b.Property<string>("name")
                        .IsRequired();

                    b.Property<int>("orderCount");

                    b.Property<string>("prices")
                        .IsRequired();

                    b.Property<int>("seen");

                    b.Property<string>("size")
                        .IsRequired();

                    b.Property<double>("version");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.HasIndex("companyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Atlob_Dent.Data.User", b =>
                {
                    b.Property<string>("phone")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("consumedProducts");

                    b.HasKey("phone");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Category", b =>
                {
                    b.HasOne("Atlob_Dent.Data.Category", "SuperCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("superId");
                });

            modelBuilder.Entity("Atlob_Dent.Data.Comment", b =>
                {
                    b.HasOne("Atlob_Dent.Data.User", "user")
                        .WithMany()
                        .HasForeignKey("phone")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atlob_Dent.Data.OnSale", b =>
                {
                    b.HasOne("Atlob_Dent.Data.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atlob_Dent.Data.Order", b =>
                {
                    b.HasOne("Atlob_Dent.Data.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Atlob_Dent.Data.Product", b =>
                {
                    b.HasOne("Atlob_Dent.Data.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Atlob_Dent.Data.Company", "company")
                        .WithMany("products")
                        .HasForeignKey("companyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
